### ISSUE TITLE
Problems with 

### ISSUE THREAD

**Issue by toomuchbrandy** [gurnec/decrypt_bitcoinj_seed#1]
Hi Gurnec, sorry to bother you but I'm having massive issues with Multibit HD wallet. I quickly set up a wallet with them following a recent rumour I'd heard of a security compromise from Jaxx. I'd had issues with MBHD in the past but wanted BTC out of Jaxx immediately figuring I could rely on multibit at least for an hour or two whilst I researched a more secure alternative. Long story short, I had to restart my machine and have ended up locked out of my wallet. After searching around I've found that loads of people have had the same issues but thanks to how fleeting I planned my time with MB I didn't note down the seed phrase (idiotic of me, I know). I've since gone round in circles trying to restore my keys and keep finding myself directed to this GitHub. I've run through the steps as carefully as my limited skills will allow, and have managed to install the program correctly. Only it runs for around 2 minutes (green bar is frozen), and eventually crashes after saying "not responding". I'm not really that technically minded (as I'm sure you can tell), and this is my first time using Github. I hope you don't mind me commenting here, as I really don't know what else to do. You seem like the person to help me. All I have is my password, and my wallet file. I'd really appreciate your thoughts on what I might be doing wrong here.

I noticed you say tell someone to open an issue for a similar predicament here. Sorry again to bother you with such newbish questions: 
https://bitcoin.stackexchange.com/questions/49995/how-can-i-recover-my-multibit-hd-wallet-words?newreg=b5a1973796c74e029be5fee9beba4fa1

**Comment by gurnec** [comment]
> ended up locked out of my wallet.
> ...
> All I have is my password, and my wallet file.

If you have your password and wallet file, then you should be able to log into it normally with MultiBit HD, correct? Is that not working for you?

> it runs for around 2 minutes (green bar is frozen)

Are you waiting long enough? Don't try to close it, just let it sit there for several minutes. It *should* eventually respond, assuming the password was correct.

> and eventually crashes

If it's crashing on its own (without you trying to close it), you can try running it via the command line to see if there are any error messages:

 * Copy your `mbhd.wallet.aes` wallet file into the same directory as the `decrypt_bitcoinj_seed.pyw` script.
 * Next (assuming you're on Windows 10), towards the upper-left of the explorer (folder) window, there's a `File` button. Click it, and then click `Open Windows PowerShell`.
 * Type this into the command prompt (all one line): ` C:\Python27\python.exe decrypt_bitcoinj_seed.pyw mbhd.wallet.aes`
 * When asked, type in your password. FYI you will not see anything as you type in your password (the cursor won't even move); this is normal.
 * After your password, press the <kbd>Enter↵</kbd> key. The cursor will move down to the next line.
 * Wait... eventually (after a few minutes) either your seed phrase or an error message should be displayed.

If you get an error message back, please report back with it (all of it) and I'll try to figure out what went wrong.

**Comment by toomuchbrandy** [comment]
Hi thanks for your great work, and your response. 

I was able to fix the issue using the advice of HardCore Pawn listed below. Combined your help has saved my butt. Thank you again. 

https://github.com/HardCorePawn/multibit_recovery

**Comment by gurnec** [comment]
Glad you got everything back, cheers!
